#!/usr/bin/env bash
set -e
url=${1:-"https://docs.google.com/uc?export=download&id=0B0F-aqLyFk_PdkpGS3YtbVFVdG8"}
echo "URL: $url"
filename="generated.tar.gz"
wget "$url" -O "$filename" || curl "$url" -L -o "$filename"
tar -xzf "$filename" 16x16 22x22 24x24 32x32 48x48 96x96 256x256 README_generated || echo "tar exit code = $?"
minimum_size=300
actual_size=$(du -b "$filename" | cut -f 1)
rm "$filename"
if [[ "$actual_size" -lt "$minimum_size" ]]; then
    echo "** (download_all_png): CRITICAL **: $filename is too small ($actual_size bytes)!"
    exit 1
fi
