#!/usr/bin/env python
# Copyright (C) 2014 Igor Kushnir <igorkuo AT Google mail>
# License: GPL v3+ (http://www.gnu.org/copyleft/gpl.html)
# common-ending-generate-qrc.py: end of script for creating qrc file for icons.

import os

def rindex_nth(haystack, needle, n):
    i = len(haystack)
    while n > 0:
        i = haystack.rindex(needle, 0, i)
        n -= 1
    return i

def get_alias(image_file):
    index = rindex_nth(image_file, '/', 3) + 1
    return image_file[index:]

def end_generating_qrc(path_to_theme, filename, images, script_name):
    index_name="index.theme"
    index_file = os.path.join(path_to_theme, index_name)

    header = """\
<!DOCTYPE RCC>
<!-- This file was auto-generated by %s -->
<RCC version="1.0">
    <qresource prefix="icons/SimpleFugue">
        <file alias="%s">%s</file>
""" % (script_name, index_name, index_file)

    trailer = """\
    </qresource>
</RCC>
"""

    with open(filename, "w") as f:
        f.write(header)
        for img in images:
            f.write('        <file alias="%s">%s</file>\n'
                                                    % (get_alias(img), img))
        f.write(trailer)
