#!/usr/bin/env bash
# Copyright (C) 2014 Igor Kushnir <igorkuo AT Google mail>
# License: GPL v3+ (http://www.gnu.org/copyleft/gpl.html)
# generate_png: uses inkscape to convert image to png format.
# If png file already exists, it is not generated and not overwritten.
set -e
# Script takes 3 parameters:
filename="$1"           # Source file name.
size="$2"               # Size of the resulting (square) png icon [int].
destination_dir="$3"    # Directory where file with the same stem as filename
# but "png" extension will be created.


# Brief: takes 4 parameters - names of floating-point variables: a0, b0, a1, b1
# (a represents x, b represents y) OR (a represents y, b represents x).
# 2 first parameters' initial values mean nothing, they are output parameters.
# 2 last parameters are input and output parameters.
# Fourth parameter's value must be not greater than third one's.
# Sets a0 to 0; sets b0 and b1 in such a way that (a1-a0==b1-b0) &&
# ((b1-b0)/2 == initial_b1/2).
center24() {
    local _greater _less _half
    eval "_greater=\$$3"
    eval "_less=\$$4"
    eval "_half=$( awk 'BEGIN{ print ("'$_greater'"-"'$_less'")/2 }' )"

    eval "$1=0"
    eval "$2=-$_half"
    # $3 is already set.
    eval "$4=$( awk 'BEGIN{ print "'$_less'"+"'$_half'" }' )"
}

if [[ -f "$filename" ]]; then
    stem=$(basename "$filename")
    if [[ "${stem::1}" == "." || "${stem: -1}" == "~" ]]; then
        exit 1
    fi

    stem="${stem%.*}"
    destination="$destination_dir/${stem}.png"

    if [ ! -f "$destination" ]; then
        command="inkscape -z"
        x1=$($command -W "$filename")
        y1=$($command -H "$filename")
        x1_less=$(awk 'BEGIN{ print "'$x1'"<"'$y1'" }')
        if [ "$x1_less" -eq 1 ]; then
            center24 y0 x0 y1 x1
        else
            center24 x0 y0 x1 y1
        fi

        $command -e "$destination" -w $size -h $size \
                    -a $x0:$y0:$x1:$y1 "$filename"

        if [ ! -f "$destination" ]; then
            exit 1
        fi
    fi
fi
